Repository marcosdosea/FrotaPublica, pull requests merged in 2024-12, with the labels that each got.

#150 Autenticação com cpf agora
  Codigo/Frota/FrotaWeb/Areas/Identity/Pages/Account/Login.cshtml
  Codigo/Frota/FrotaWeb/Areas/Identity/Pages/Account/Login.cshtml.cs
  Codigo/Frota/FrotaWeb/Areas/Identity/Pages/Account/Register.cshtml
  Codigo/Frota/FrotaWeb/Areas/Identity/Pages/Account/Register.cshtml.cs
  Codigo/Frota/FrotaWeb/Views/Shared/_Layout.cshtml
Labels: enhancement

#155 Adicionada mácara de cpf para autenticação e menu aprimorado
  Codigo/Frota/FrotaWeb/Areas/Identity/Pages/Account/Login.cshtml
  Codigo/Frota/FrotaWeb/Areas/Identity/Pages/Account/Login.cshtml.cs
  Codigo/Frota/FrotaWeb/Areas/Identity/Pages/Account/Register.cshtml
  Codigo/Frota/FrotaWeb/Areas/Identity/Pages/Account/Register.cshtml.cs
  Codigo/Frota/FrotaWeb/wwwroot/css/navBar.css
  Codigo/Frota/FrotaWeb/wwwroot/js/authentication.js
Labels: enhancement

#157 Correção na duplicação de email ou cpf ao resgistrar-se
  Codigo/Frota/FrotaWeb/Areas/Identity/Pages/Account/Register.cshtml.cs
  Codigo/Frota/FrotaWeb/wwwroot/js/authentication.js
Labels: correction

#158 Implementação da paginação da index de condutores/pessoas
  AnaliseProjeto/dump-frota.sql
  Codigo/Frota/FrotaWeb/Controllers/PessoaController.cs
  Codigo/Frota/FrotaWeb/Views/Pessoa/Index.cshtml
  Codigo/Frota/FrotaWeb/Views/Shared/_Layout.cshtml
  Codigo/Frota/FrotaWeb/wwwroot/css/index-pages.css
  Codigo/Frota/FrotaWeb/wwwroot/img/logo.svg
  Codigo/Frota/FrotaWeb/wwwroot/js/navBar.js
Labels: enhancement

#160 Implementação da paginação para veículos
  Codigo/Frota/FrotaWeb/Controllers/VeiculoController.cs
  Codigo/Frota/FrotaWeb/Views/Veiculo/Index.cshtml
  Codigo/Frota/FrotaWeb/wwwroot/css/index-pages.css
Labels: enhancement

#163 Implementada a paginação da index de percurso
  Codigo/Frota/FrotaWeb/Controllers/PercursoController.cs
  Codigo/Frota/FrotaWeb/Views/Percurso/Index.cshtml
  Codigo/Frota/FrotaWeb/Views/Shared/_Layout.cshtml
  Codigo/Frota/FrotaWeb/wwwroot/css/index-pages.css
Labels: enhancement

#164 Implementação da paginação de manutenções
  Codigo/Frota/FrotaWeb/Controllers/AbastecimentoController.cs
  Codigo/Frota/FrotaWeb/Controllers/FornecedorController.cs
  Codigo/Frota/FrotaWeb/Controllers/FrotaController.cs
  Codigo/Frota/FrotaWeb/Controllers/ManutencaoController.cs
  Codigo/Frota/FrotaWeb/Controllers/ManutencaoPecaInsumoController.cs
  Codigo/Frota/FrotaWeb/Controllers/MarcaPecaInsumoController.cs
  Codigo/Frota/FrotaWeb/Controllers/MarcaVeiculoController.cs
  Codigo/Frota/FrotaWeb/Controllers/ModeloVeiculoController.cs
  Codigo/Frota/FrotaWeb/Controllers/PecaInsumoController.cs
  Codigo/Frota/FrotaWeb/Controllers/SolicitacaoManutencaoController.cs
  Codigo/Frota/FrotaWeb/Controllers/UnidadeAdministrativaController.cs
  Codigo/Frota/FrotaWeb/Controllers/VeiculoPecaInsumoController.cs
  Codigo/Frota/FrotaWeb/Controllers/VistoriaController.cs
  Codigo/Frota/FrotaWeb/Views/Manutencao/Index.cshtml
  Codigo/Frota/FrotaWeb/wwwroot/css/index-pages.css
Labels: enhancement

#177 Implementação da melhoria da paginação na index de pessoas/condutores
  Codigo/Frota/Core/Service/IPessoaService.cs
  Codigo/Frota/FrotaWeb/Controllers/PessoaController.cs
  Codigo/Frota/Service/PessoaService.cs
Labels: correction

#199 Correção na configuração de sessão na aplicação
  Codigo/Frota/FrotaWeb/Program.cs
Labels: correction

#197 Criação do dump de dados
  AnaliseProjeto/dump-frota-dados.sql
  AnaliseProjeto/readme.txt
Labels: documentation

#178 Melhoria e implementação da index de pessoas/condutores, close #174
  Codigo/Frota/Core/Service/IPessoaService.cs
  Codigo/Frota/FrotaWeb/Controllers/PessoaController.cs
  Codigo/Frota/FrotaWeb/Models/PessoaViewModel.cs
  Codigo/Frota/FrotaWeb/Views/Pessoa/Index.cshtml
  Codigo/Frota/FrotaWeb/wwwroot/css/index-pages.css
  Codigo/Frota/Service/PessoaService.cs
Labels: correction
