Repository marcosdosea/FrotaPublica, pull requests merged in 2025-01, with the labels that each got.

#202 Ajustes nos testes de unidade e integração
  Codigo/Frota/FrotaWebTests/Controllers/AbastecimentoControllerTests.cs
  Codigo/Frota/FrotaWebTests/Controllers/FornecedorControllerTests.cs
  Codigo/Frota/FrotaWebTests/Controllers/FrotaControllerTests.cs
  Codigo/Frota/FrotaWebTests/Controllers/PessoaControllerTests.cs
  Codigo/Frota/FrotaWebTests/Controllers/VeiculoControllerTests.cs
  Codigo/Frota/Service/FrotaService.cs
  Codigo/Frota/Service/PessoaService.cs
  Codigo/Frota/Service/VeiculoService.cs
  Codigo/Frota/ServiceTests/FrotaServiceTests.cs
  Codigo/Frota/ServiceTests/PessoaServiceTests.cs
  Codigo/Frota/ServiceTests/VeiculoServiceTests.cs
Labels: correction

#203 Foram feitos os ajustes necessários para Manter Abastecimento
  Codigo/Frota/Core/Abastecimento.cs
  Codigo/Frota/Core/Fornecedor.cs
  Codigo/Frota/Core/FrotaContext.cs
  Codigo/Frota/Core/Frotum.cs
  Codigo/Frota/Core/Manutencao.cs
  Codigo/Frota/Core/Manutencaopecainsumo.cs
  Codigo/Frota/Core/Marcapecainsumo.cs
  Codigo/Frota/Core/Marcaveiculo.cs
  Codigo/Frota/Core/Modeloveiculo.cs
  Codigo/Frota/Core/Pecainsumo.cs
  Codigo/Frota/Core/Percurso.cs
  Codigo/Frota/Core/Pessoa.cs
  Codigo/Frota/Core/Service/IAbastecimentoService.cs
  Codigo/Frota/Core/Service/IPessoaService.cs
  Codigo/Frota/Core/Solicitacaomanutencao.cs
  Codigo/Frota/Core/Unidadeadministrativa.cs
  Codigo/Frota/Core/Veiculo.cs
  Codigo/Frota/FrotaWeb/Controllers/AbastecimentoController.cs
  Codigo/Frota/FrotaWeb/FrotaWeb.csproj.user
  Codigo/Frota/FrotaWeb/Models/AbastecimentoViewModel.cs
  Codigo/Frota/FrotaWeb/Views/Abastecimento/Create.cshtml
  Codigo/Frota/FrotaWeb/Views/Abastecimento/Delete.cshtml
  Codigo/Frota/FrotaWeb/Views/Abastecimento/Details.cshtml
  Codigo/Frota/FrotaWeb/Views/Abastecimento/Edit.cshtml
  Codigo/Frota/Service/AbastecimentoService.cs
  Codigo/Frota/Service/PessoaService.cs
Labels: correction

#209 Refatoração na controladora de fornecedor
  Codigo/Frota/FrotaWeb/Controllers/FornecedorController.cs
  Codigo/Frota/Service/FornecedorService.cs
  Codigo/Frota/Service/Service.csproj
Labels: enhancement

#210 Peça/Insumo associada a frota
  AnaliseProjeto/readme.txt
  Codigo/Frota/Core/Service/IPecaInsumoService.cs
  Codigo/Frota/FrotaWeb/Controllers/PecaInsumoController.cs
  Codigo/Frota/FrotaWeb/Controllers/VeiculoPecaInsumoController.cs
  Codigo/Frota/Service/PecaInsumoService.cs
Labels: enhancement, correction

#213 Template para prs adicionado
  .github/pull_request_template.md
Labels: documentation

#215 Implementados os ajustes na marca veículo, close #189
  Codigo/Frota/Core/Service/IMarcaVeiculoService.cs
  Codigo/Frota/FrotaWeb/Controllers/MarcaVeiculoController.cs
  Codigo/Frota/FrotaWeb/Models/MarcaVeiculoViewModel.cs
  Codigo/Frota/Service/MarcaVeiculoService.cs
Labels: enhancement, correction

#214 Associação de modelos de veículos com a frota
  Codigo/Frota/Core/Service/IModeloVeiculoService.cs
  Codigo/Frota/Core/Service/IUnidadeAdministrativaService.cs
  Codigo/Frota/Core/Service/IVeiculoService.cs
  Codigo/Frota/FrotaWeb/Controllers/ModeloVeiculoController.cs
  Codigo/Frota/FrotaWeb/Controllers/UnidadeAdministrativaController.cs
  Codigo/Frota/FrotaWeb/Controllers/VeiculoController.cs
  Codigo/Frota/Service/ModeloVeiculoService.cs
  Codigo/Frota/Service/UnidadeAdministrativaService.cs
  Codigo/Frota/Service/VeiculoService.cs
Labels: enhancement, correction

#216 Campos adicionados em peça/insumo
  Codigo/Frota/FrotaWeb/Models/PecaInsumoViewModel.cs
Labels: enhancement

#217 Corrigir erros de compilação nos testes de integração
  Codigo/Frota/Core/Core.csproj
  Codigo/Frota/Core/DTO/VeiculoDTO.cs
  Codigo/Frota/Core/Pecainsumo.cs
  Codigo/Frota/Core/Service/IPessoaService.cs
  Codigo/Frota/Core/Service/IVeiculoService.cs
  Codigo/Frota/Core/Service/ServiceException.cs
  Codigo/Frota/Core/Unidadeadministrativa.cs
  Codigo/Frota/FrotaWeb/Controllers/VeiculoController.cs
  Codigo/Frota/Service/AbastecimentoService.cs
  Codigo/Frota/Service/FrotaService.cs
  Codigo/Frota/Service/PessoaService.cs
  Codigo/Frota/Service/VeiculoService.cs
  Codigo/Frota/ServiceTests/AbastecimentoServiceTests.cs
  Codigo/Frota/ServiceTests/FornecedorServiceTests.cs
  Codigo/Frota/ServiceTests/FrotaServiceTests.cs
  Codigo/Frota/ServiceTests/ManutencaoPecaInsumoServiceTests.cs
  Codigo/Frota/ServiceTests/ManutencaoServiceTests.cs
  Codigo/Frota/ServiceTests/MarcaPecaInsumoServiceTests.cs
  Codigo/Frota/ServiceTests/MarcaVeiculoServiceTests.cs
  Codigo/Frota/ServiceTests/ModeloVeiculoServiceTests.cs
  Codigo/Frota/ServiceTests/PecaInsumoServiceTests.cs
  Codigo/Frota/ServiceTests/PercursoServiceTests.cs
  Codigo/Frota/ServiceTests/PessoaServiceTests.cs
  Codigo/Frota/ServiceTests/ServiceTests.csproj
  Codigo/Frota/ServiceTests/SolicitacaoManutencaoServiceTests.cs
  Codigo/Frota/ServiceTests/UnidadeAdministrativaServiceTests.cs
  Codigo/Frota/ServiceTests/VeiculoPecaInsumoServiceTests.cs
  Codigo/Frota/ServiceTests/VeiculoServiceTests.cs
Labels: correction

#221 Corrigir erros de compilação nos testes de unidade
  Codigo/Frota/Core/Core.csproj
  Codigo/Frota/Core/Service/IFornecedorService.cs
  Codigo/Frota/FrotaWeb/Controllers/AbastecimentoController.cs
  Codigo/Frota/FrotaWebTests/Controllers/AbastecimentoControllerTests.cs
  Codigo/Frota/FrotaWebTests/Controllers/FornecedorControllerTests.cs
  Codigo/Frota/FrotaWebTests/Controllers/FrotaControllerTests.cs
  Codigo/Frota/FrotaWebTests/Controllers/ManutencaoControllerTests.cs
  Codigo/Frota/FrotaWebTests/Controllers/MarcaPecaInsumoControllerTests.cs
  Codigo/Frota/FrotaWebTests/Controllers/MarcaVeiculoControllerTests.cs
  Codigo/Frota/FrotaWebTests/Controllers/ModeloVeiculoControllerTests.cs
  Codigo/Frota/FrotaWebTests/Controllers/PecaInsumoControllerTests.cs
  Codigo/Frota/FrotaWebTests/Controllers/PercursoControllerTests.cs
  Codigo/Frota/FrotaWebTests/Controllers/PessoaControllerTests.cs
  Codigo/Frota/FrotaWebTests/Controllers/SolicitacaoManutencaoControllerTests.cs
  Codigo/Frota/FrotaWebTests/Controllers/UnidadeAdministrativaControllerTests.cs
  Codigo/Frota/FrotaWebTests/Controllers/VeiculoControllerTests.cs
  Codigo/Frota/FrotaWebTests/Controllers/VeiculoPecaInsumoControllerTests.cs
  Codigo/Frota/FrotaWebTests/Controllers/VistoriaControllerTests.cs
  Codigo/Frota/ServiceTests/FornecedorServiceTests.cs
  Codigo/Frota/ServiceTests/ManutencaoServiceTests.cs
  Codigo/Frota/ServiceTests/ServiceTests.csproj
  Codigo/Frota/ServiceTests/VeiculoServiceTests.cs
Labels: correction
